const Data = [
  {
  "recordType": "Adult Group",
  "timeZone": "UTC−05:00",
  "time": "01:00 PM",
  "slugCampusName": "asheville",
  "searchable": true,
  "schedule": "Biweekly",
  "name": "Learning through Living & Lunching Women's eGroup (Gerri Stover)",
  "meetingType": "In-person",
  "locationZipCode": "",
  "locationName": "Various locations around Arden and South Asheville",
  "language": "English",
  "gender": "Female",
  "egroupType": "eGroup Specific Study",
  "egroupStudy": "eGroup Specific Study - eGroup Specific Study",
  "description": "We are a women's group that will gather to build community and enjoy life together. We will connect through various fun activities or lunch to grow in faith and in life.",
  "demographic": "Gender Specific",
  "dayOfWeek": "Sunday",
  "childCare": false,
  "campusName": "Asheville",
  "active": true,
  "id": "a0A0QpYA1"
  },
  {
  "recordType": "Adult Group",
  "timeZone": "UTC−05:00",
  "time": "07:00 PM",
  "slugCampusName": "greensboro",
  "searchable": true,
  "schedule": "Weekly",
  "name": "Greensboro: Everyone Welcome - Sharon Elwood",
  "meetingType": "Virtual",
  "makeLocationVisible": true,
  "locationZipCode": "",
  "locationName": "Zoom",
  "language": "English",
  "gender": "CoEd",
  "egroupType": "Women",
  "egroupStudy": "Women - Trustworthy",
  "description": "This group will be about finding tools to help connect and grow stronger faith with like minded individuals. To help encourage, promote doing life together and not alone during all walks of life.",
  "demographic": "Everyone Welcome",
  "dayOfWeek": "Monday",
  "childCare": false,
  "campusName": "Greensboro",
  "active": true,
  "id": "a0A0R0nAD"
  },
  {
  "recordType": "Adult Group",
  "timeZone": "UTC−05:00",
  "time": "06:30 PM",
  "slugCampusName": "ballantyne",
  "searchable": true,
  "schedule": "Biweekly",
  "name": "Women’s Sermon Discussion (Cindy Hazen)",
  "meetingType": "In-person",
  "locationZipCode": "28134",
  "locationName": "Cindy’s Home",
  "language": "English",
  "gender": "Female",
  "egroupType": "Sermon Discussion",
  "egroupStudy": "Sermon Discussion - Sermon Discussion",
  "description": "If you’re looking for a group of women to do this messy life with, come join us! We’re 40-60 yrs old- but any age is welcome. We’d love to have you ❤️",
  "demographic": "Gender Specific",
  "dayOfWeek": "Wednesday",
  "childCare": false,
  "campusName": "Ballantyne",
  "active": true,
  "id": "a0A0sJkAV"
  },
  {
  "recordType": "Adult Group",
  "schedule": "Weekly",
  "name": "Cambios - Jóvenes Adultos Mixto (20-35 años)",
  "meetingType": "Virtual",
  "makeLocationVisible": true,
  "locationZipCode": "",
  "locationName": "ONLINE | Eastern Standard Time",
  "language": "Spanish",
  "gender": "CoEd",
  "egroupType": "Sermon Discussion",
  "egroupStudy": "Sermon Discussion - Sermon Discussion",
  "description": "Jóvenes adultos. Únete a mi grupo en Español",
  "demographic": "Everyone Welcome",
  "dayOfWeek": "Wednesday",
  "childCare": false,
  "campusName": "Elevation Online",
  "active": true,
  "id": "a0w0X7CA1"
  },
  {
  "recordType": "Adult Group",
  "schedule": "Biweekly",
  "name": "Hiking eGroup - Everyone Welcome (Stephanie Netherly)",
  "meetingType": "In-person",
  "locationZipCode": "",
  "locationName": "Crowder's Mountain",
  "language": "English",
  "gender": "CoEd",
  "egroupType": "eGroup Specific Study",
  "egroupStudy": "eGroup Specific Study - eGroup Specific Study",
  "description": "Join us as we hike together and participate in Sermon Discussion in God's creation.",
  "demographic": "Everyone Welcome",
  "dayOfWeek": "Saturday",
  "childCare": false,
  "campusName": "Ballantyne",
  "active": true,
  "id": "a0w0X7JAL"
  },
  {
  "recordType": "Adult Group",
  "schedule": "Weekly",
  "name": "Desiring More - Bible Basics 101 (Melissa Simmons)",
  "meetingType": "Virtual",
  "locationZipCode": "",
  "locationName": "Zoom",
  "language": "English",
  "gender": "CoEd",
  "egroupType": "eGroup Specific Study",
  "egroupStudy": "eGroup Specific Study - eGroup Specific Study",
  "description": "This is group is for anyone looking to learn the foundations of our beliefs and about God's love for them.",
  "demographic": "Everyone Welcome",
  "dayOfWeek": "Wednesday",
  "childCare": false,
  "campusName": "Ballantyne",
  "active": true,
  "id": "a0w0X7JA1"
  },
  {
  "recordType": "Adult Group",
  "schedule": "Weekly",
  "name": "Intentional Parenting & Prayer- Women's eGroup (Shawna Scott)",
  "meetingType": "In-person",
  "locationZipCode": "",
  "locationName": "Leader's Home in South Asheville",
  "language": "English",
  "gender": "Female",
  "egroupType": "eGroup Specific Study",
  "egroupStudy": "eGroup Specific Study - eGroup Specific Study",
  "description": "Join us as come come together as mothers to form community and intentionally build our faith. We will be reading \"Parenting\" by Paul David Tripp together and having focused prayer time.",
  "demographic": "Gender Specific",
  "dayOfWeek": "Tuesday",
  "childCare": true,
  "campusName": "Asheville",
  "active": true,
  "id": "a0w0X7GA1"
  },
  {
  "recordType": "Adult Group",
  "timeZone": "UTC−05:00",
  "time": "7:00 PM",
  "slugCampusName": "ballantyne",
  "searchable": true,
  "schedule": "Biweekly",
  "name": "Women of all Generations (Nicole Wolf & Dorie Julian)",
  "meetingType": "Virtual",
  "locationZipCode": "29708",
  "locationName": "Fort Mill",
  "language": "English",
  "gender": "Female",
  "egroupType": "",
  "egroupStudy": "",
  "description": "This is a women's sermon study group led by a mother and daughter. We are all either mothers or daughters, and we would love to grow in relationship with God and each other with you!",
  "demographic": "Gender Specific",
  "dayOfWeek": "Wednesday",
  "childCare": false,
  "campusName": "Ballantyne",
  "active": true,
  "id": "a0w0X7TAL"
  },
  {
  "recordType": "Adult Group",
  "timeZone": "UTC−05:00",
  "time": "07:00 PM",
  "slugCampusName": "orlando",
  "searchable": true,
  "schedule": "Weekly",
  "name": "Young Adults: South Orlando (Dannie & Katelyn)",
  "meetingType": "Virtual",
  "locationZipCode": "32822",
  "locationName": "Leader's home",
  "language": "English",
  "gender": "CoEd",
  "egroupType": "Sermon Discussion",
  "egroupStudy": "Sermon Discussion - Sermon Discussion",
  "description": "A safe place for young adults seeking deeper relationships.",
  "demographic": "Everyone Welcome",
  "dayOfWeek": "Wednesday",
  "childCare": false,
  "campusName": "Orlando",
  "active": true,
  "id": "a0w0RMoAH"
  }
 ]

 export default Data;